"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Weapon_1 = require("./Weapon");
const Spell_1 = require("./Spell");
const Warrior_1 = require("./Warrior");
const Mage_1 = require("./Mage");
const Party_1 = require("./Party");
const longsword = new Weapon_1.weapon("Longsword", 35);
const battleAxe = new Weapon_1.weapon("Battle Axe", 45);
const fireball = new Spell_1.Spell("Fireball", 50, 30);
const iceBolt = new Spell_1.Spell("Ice Bolt", 30, 10);
const aragorn = new Warrior_1.Warrior("Aragorn", 10, 150, 0, longsword);
const gimli = new Warrior_1.Warrior("Gimli", 9, 160, 0, battleAxe);
const gandalf = new Mage_1.Mage("Gandalf", 12, 100, 100, fireball);
const merlin = new Mage_1.Mage("Merlin", 8, 80, 100, iceBolt);
const theDragonSlayers = new Party_1.Party("The Dragon Slayers");
theDragonSlayers.addMember(aragorn);
theDragonSlayers.addMember(gimli);
theDragonSlayers.addMember(gandalf);
theDragonSlayers.addMember(merlin);
console.log("Party Members:");
theDragonSlayers.showMembers();
console.log("");
aragorn.attack();
gimli.attack();
console.log("");
gandalf.castSpell();
merlin.castSpell();
console.log("");
console.log(gandalf.getName() + " takes 40 damage!");
gandalf.takeDamage(40);
console.log("Health remaining: " + gandalf.getHealth());
console.log("");
theDragonSlayers.removeMember(gimli);
console.log("Party after removing Gimli:");
theDragonSlayers.showMembers();
